### ISSUE TITLE
error has no exported member 'NgProgressCustomBrowserXhr'

### ISSUE THREAD

**Issue by reza3vi** [MurhafSousli/ngx-progressbar#44]
ngx-progressbar -> error has no exported member 'NgProgressCustomBrowserXhr'

**Comment by reza3vi** [comment]
NgProgressCustomBrowserXhr -> NgProgressBrowserXhr

**Comment by MurhafSousli** [comment]
@reza3vi I just published a new release now, Update to v2.0.2

**Comment by dhardtke** [comment]
With version 2.0.1 / 2.0.2 our client no longer works after compiling it (Yes, I use NgProgressBrowserXhr):

Could it be that you have broken the AOT compilation? When running the compiled client using webpack (without minification) I get:

![38160526_2017-06-15_00-19-32](https://user-images.githubusercontent.com/1360135/27157103-558ad726-5160-11e7-9ca6-7cee98bc6d26.png)

**Comment by reza3vi** [comment]
![untitled](https://user-images.githubusercontent.com/20870866/27158085-46a5fa46-517a-11e7-9e59-995bf56a2a3b.png)
error in build aot

**Comment by MurhafSousli** [comment]
@dhardtke @reza3vi Each one of you is getting different errors! are you using systemjs or the angular-cli?

**Comment by dhardtke** [comment]
I get the errors I posted when I try to load the application in my browser. Compiling works just fine.

I am compiling using webpack with https://github.com/angular/angular-cli/tree/master/packages/%40ngtools/webpack (which is part of angular-cli btw)

**Comment by MurhafSousli** [comment]
The new workflow has mixed things up, I will investigate about this error

**Comment by dhardtke** [comment]
With 2.0.2 I'm getting the same errors as reza3vi.

**Comment by reza3vi** [comment]
i'm using angular cli

**Comment by MurhafSousli** [comment]
@reza3vi `npm install ngx-progressbar@2.0.0`

**Comment by reza3vi** [comment]
npm install ngx-progressbar@2.0.0 -> i get invalid error.

**Comment by reza3vi** [comment]
thanks. resolve.

**Comment by MurhafSousli** [comment]
@reza3vi @dhardtke fixed in **v2.0.3**, tested for AOT :+1:

**Comment by reza3vi** [comment]
thanks. work for me! ;)

**Comment by Wandang** [comment]
I am using v2.0.3 (  "ngx-progressbar": "^2.0.3") and still have that error.

Using Angular CLI 4.0.0

**Comment by MurhafSousli** [comment]
@Wandang Please include your usage code, note that `NgProgressCustomBrowserXhr` is now `NgProgressBrowserXhr`

**Comment by Wandang** [comment]
my bad
